// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQRaQSYwE-DrAaxK5jFVDODn3w5avQSM',
    appId: '1:62140501375:web:f8f3b698d9fa12d31ede4a',
    messagingSenderId: '62140501375',
    projectId: 'codex-fd4a2',
    authDomain: 'codex-fd4a2.firebaseapp.com',
    storageBucket: 'codex-fd4a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTQ9XasEKQRv-IHgqeSBQ9_U22Ml6MMA',
    appId: '1:62140501375:android:6fa01ed0b4a5886a1ede4a',
    messagingSenderId: '62140501375',
    projectId: 'codex-fd4a2',
    storageBucket: 'codex-fd4a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcVkwCK04W_-EO3Ra2s8u8NvzwDevEtWY',
    appId: '1:62140501375:ios:edea052a4471f24b1ede4a',
    messagingSenderId: '62140501375',
    projectId: 'codex-fd4a2',
    storageBucket: 'codex-fd4a2.appspot.com',
    iosBundleId: 'com.example.codex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcVkwCK04W_-EO3Ra2s8u8NvzwDevEtWY',
    appId: '1:62140501375:ios:edea052a4471f24b1ede4a',
    messagingSenderId: '62140501375',
    projectId: 'codex-fd4a2',
    storageBucket: 'codex-fd4a2.appspot.com',
    iosBundleId: 'com.example.codex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFQRaQSYwE-DrAaxK5jFVDODn3w5avQSM',
    appId: '1:62140501375:web:0425ee0428b739d91ede4a',
    messagingSenderId: '62140501375',
    projectId: 'codex-fd4a2',
    authDomain: 'codex-fd4a2.firebaseapp.com',
    storageBucket: 'codex-fd4a2.appspot.com',
  );
}
